Issue 21 feat/UI prepare home screen
coders-camp-2021-best-team/FitaTAM pull request #23
Opened 2022-05-06 19:30 UTC by Mariusz-web

2022-05-09 19:03 UTC, Veryyapeee commented
IMO that should be centered vertically
![Screenshot 2022-05-09 at 21 02 37](https://user-images.githubusercontent.com/43120132/167479489-c9490b78-bbe8-4052-b839-1d6d246b7443.png)

2022-05-09 19:07 UTC, Veryyapeee requested changes

2022-05-09 19:07 UTC, Veryyapeee commented on apps/client/src/app/Router.tsx
> +                    <Route path={ROUTES.HOME} element={<Home />} />
why did you added home route here, and commented the one above? xd

2022-05-09 19:07 UTC, Veryyapeee commented on apps/client/src/app/sceens/BaseScreen/BaseScreen.tsx
> +            {/* {isLogged ? <Header /> : null} */}
why is it commented?

2022-05-09 19:07 UTC, Veryyapeee commented on apps/client/src/app/sceens/Home/Home.styles.ts
> +export const homeStyle = {
we could use emotion in here, which is by default dependency of MUI

2022-05-09 19:44 UTC, Mariusz-web commented on apps/client/src/app/sceens/BaseScreen/BaseScreen.tsx
> +            {/* {isLogged ? <Header /> : null} */}
I forgot to change it

2022-05-12 11:50 UTC, Veryyapeee approved these changes
Looks good, remember to uncomment code that you commented for testing purposes

2022-05-12 18:06 UTC, merged